"""add user

Revision ID: d05e7296bc8f
Revises: 3bfddbdec75c
Create Date: 2021-01-21 09:24:14.732117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05e7296bc8f'
down_revision = '3bfddbdec75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
